- src: geerlingguy.docker
  version: 2.5.3
- src: andrewrothstein.kubectl
  version: v1.1.54
- src: andrewrothstein.minikube
  version: v1.5.31
- src: andrewrothstein.kubernetes-helm
  version: v1.3.4
- src: diodonfrost.terraform
  version: 1.0.2
- src: andrewrothstein.vault
  version: v1.2.27
- src: huxoll.azure-cli
  version: 1.1.1
- src: gantsign.golang
  version: 2.9.2
- src: andrewrothstein.scala
  version: v3.1.10
