#!/bin/bash

set -Eeuo pipefail

KEYS_DIR="${SSH_KEYS_DIR:-${HOME}/.ssh-keys}"

function newline() {
  echo ""
}

function use_bastion() {
  local -n use_bastion=${1}
  local -n target_ip_field=${2}
  newline
  local use_bastion_default="y"
  read -p "Ssh via bastion [y/n]? (${use_bastion_default}): " -n 1 use_bastion
  use_bastion=$(echo -n "${use_bastion:-${use_bastion_default}}" | tr '[:upper:]' '[:lower:]')
  if [[ "${use_bastion}" == "y" ]]; then
    target_ip_field="private_ip"
  else
    target_ip_field="public_ip"
  fi
}

function empty_check() {
  local instances_details="${1}"
  local message="${2}"
  if [[ $(echo -n "${instances_details}" | jq 'length') -eq 0 ]]; then
    newline
    echo "${message}"
    exit 1
  fi
}

function print_options() {
  local indexed_instances_details="${1}"
  local message="${2}"
  local ip_field="${3}"

  local max_index_length=$(($(echo -n "${indexed_instances_details}" | jq '. | map(.index | tostring | length) | max') + 1))
  local max_name_length=$(($(echo -n "${indexed_instances_details}" | jq '. | map(.name | length) | max') + 1))

  newline
  echo "${message}"
  newline

  for option in $(echo -n "${indexed_instances_details}" | jq -r ".[] | {detail: ((.index|tostring) + \".|\" + (.name | gsub(\"[[:space:]]+\"; \"SPACE\")) + \"|\" + .${ip_field} )} | .detail")
  do
    index=$(echo -n "${option}" | cut -d '|' -f 1)
    name=$(echo -n "${option}" | cut -d '|' -f 2 | sed 's|SPACE| |g')
    ip=$(echo -n "${option}" | cut -d '|' -f 3)
    padded_index=$(printf %"${max_index_length}"s "${index}")
    padded_name=$(printf %-"${max_name_length}"s "${name}")
    echo "${padded_index}  ${padded_name} (${ip})"
  done
}

function select_and_set_instance_details_in_vars() {
  local -n instance_ip=${1}
  local -n instance_key=${2}
  local -n instance_user=${3}
  local instances_details=${4}
  local ip_field=${5}
  local selection_message=${6}
  indexed_instances_details=$(echo -n "${instances_details}" | jq -c ". | to_entries | map({index:.key, id:.value.id, key:.value.key, name:.value.name, private_ip:.value.private_ip, public_ip:.value.public_ip})")
  print_options "${indexed_instances_details}" "${selection_message}" "${ip_field}"
  capture_argument_with_default instance_index "Instance" "0"
  instance_ip=$(echo -n "${indexed_instances_details}" | jq -r ".[] | select(.index == ${instance_index}) | .${ip_field}")
  instance_key_pair=$(echo -n "${indexed_instances_details}" | jq -r ".[] | select(.index == ${instance_index}) | .key")
  instance_name=$(echo -n "${indexed_instances_details}" | jq -r ".[] | select(.index == ${instance_index}) | .name")
  lookup_key instance_key "${instance_key_pair}" "${instance_name}"
  instance_user instance_user "${instance_name}"
}

function filter_instances_details() {
  local -n filtered_instances_details=${1}
  local instances_details=${2}
  filtered_instances_details=$(echo -n "${instances_details}")
  for search_string in "${@:3}"
  do
    filtered_instances_details=$(echo -n "${filtered_instances_details}" | jq -c ". | map(select(.name | ascii_downcase | contains(\"$(echo "${search_string}" | tr '[:upper:]' '[:lower:]')\")))")
  done
}

function capture_argument() {
  local -n argument=${1}
  local message=${2}
  newline
  read -p "${message}: " argument
}

function capture_argument_with_default() {
  local -n argument=${1}
  local message=${2}
  local default_value=${3}
  newline
  read -p "${message} (${default_value}): " argument
  argument=${argument:-${default_value}}
}

function set_instance_details_in_vars() {
  local -n instance_ip=${1}
  local -n instance_key=${2}
  local -n instance_user=${3}
  local instance_details="${4}"
  local ip_field=${5}
  instance_ip=$(echo -n "${instance_details}" | jq -r ".${ip_field}")
  instance_key_pair=$(echo -n "${instance_details}" | jq -r ".key")
  instance_name=$(echo -n "${instance_details}" | jq -r ".name")
  lookup_key instance_key "${instance_key_pair}" "${instance_name}"
  instance_user instance_user "${instance_name}"
}

function print_batch_confirmation() {
  local instances_details="${1}"
  local message="${2}"

  newline
  echo "${message}"
  newline

  for option in $(echo -n "${instances_details}" | jq -r ".[] | .name | gsub(\"[[:space:]]+\"; \"SPACE\")")
  do
    name=$(echo -n "${option}" | sed 's|SPACE| |g')
    echo " - ${name}"
  done

  local confirmation_default="y"
  newline
  read -p "Proceed [y/n]? (y): " -n 1 confirmation
  confirmation=$(echo -n "${confirmation:-${confirmation_default}}" | tr '[:upper:]' '[:lower:]')
  if [[ "${confirmation}" != "y" ]]; then
    exit 1
  fi
}

function lookup_key() {
  local -n key_path=${1}
  local key_pair="${2}"
  local instance_name="${3}"
  local key_pair_fingerprint=$(aws ec2 describe-key-pairs --key-names "${key_pair}" | jq -r '.KeyPairs[0].KeyFingerprint')
  for key_file in $(find ${KEYS_DIR} -type f); do
    if [[ "${key_file}" != *".pub" ]]; then
      key_file_fingerprint=$(openssl pkcs8 -in "${key_file}" -nocrypt -topk8 -outform DER | openssl sha1 -c | awk '{print $2}')
      if [[ "${key_pair_fingerprint}" == "${key_file_fingerprint}" ]]; then
        key_path="${key_file}"
        break
      fi
    fi
  done
  if [[ -z "${key_path-}" ]]; then
    capture_argument key_path "Path to key for ${instance_name}"
  fi
}

function instance_user() {
  local -n user_name=${1}
  local instance_name="${2}"
  capture_argument_with_default user_name "User for ${instance_name}" "ubuntu"
}