#!/bin/bash

set -Eeuo pipefail

source "$( dirname ${BASH_SOURCE[0]} )/qssh-generic-functions"
source "$( dirname ${BASH_SOURCE[0]} )/qssh-override-functions"

ALL_INSTANCES_DETAILS=$(aws ec2 describe-instances --filters "Name=instance-state-code,Values=16" | jq -c '.Reservations | {instances: map(.Instances) | add} | .instances |=map({id: .InstanceId, key: .KeyName, name: .Tags[] | select(.Key=="Name") | .Value, vpc_id: .VpcId, private_ip: .NetworkInterfaces[0].PrivateIpAddress, public_ip: .NetworkInterfaces[0].Association.PublicIp}) | .instances |=sort_by(.name) | .instances')

filter_instances_details TARGET_INSTANCES_DETAILS "${ALL_INSTANCES_DETAILS}" "${@}"
empty_check "${TARGET_INSTANCES_DETAILS}" "No target instances found"
print_batch_confirmation "${TARGET_INSTANCES_DETAILS}" "Execute command on below instances"

capture_argument BATCH_COMMAND "Enter command to be executed on targets"
BATCH_COMMAND="echo \"executing [${BATCH_COMMAND}] in \$(hostname -I | awk '{print \$1}')\"; echo ''; ${BATCH_COMMAND} || true; echo ''"

for INSTANCE_DETAILS in $(echo -n "${TARGET_INSTANCES_DETAILS}" | jq -c '.[]' | sed 's| |SPACE|g'); do
  set_instance_details_in_vars TARGET_IP TARGET_KEY TARGET_USER TARGET_VPC USE_BASTION "${INSTANCE_DETAILS}"
  newline
  if [[ "${USE_BASTION}" == "y" ]]; then
    choose_bastion BASTION_IP BASTION_KEY BASTION_USER "${ALL_INSTANCES_DETAILS}" "${TARGET_VPC}"
    ssh -q -o StrictHostKeyChecking=no \
      -o ProxyCommand="ssh -q -o StrictHostKeyChecking=no -i ${BASTION_KEY} ${BASTION_USER}@${BASTION_IP} -W %h:%p" \
      -i ${TARGET_KEY} ${TARGET_USER}@${TARGET_IP} ${BATCH_COMMAND}
  else
    ssh -q -o StrictHostKeyChecking=no \
      -i ${TARGET_KEY} ${TARGET_USER}@${TARGET_IP} ${BATCH_COMMAND}
  fi
done